### PR TITLE
Update RateDistortionLoss

### PR DESCRIPTION
**Pull request by Freed-Wu**
Add Q2LAMBDA
Add q, metric, return_type to RateDistortionLoss's __init__()

### CODE REVIEW

**Comment by Do1e** [comment]
I think function ms_ssim should set `data_range=1.0`

**Comment by Freed-Wu** [comment]
You are right. Fixed.

**Comment by fracape** [comment]
Hi, thanks for the PR. Please check linting issues. We can add ms-ssim RD-loss. However, having the mapping between "qualities" and lambdas hard-coded might not be very helpful, they were chosen by the authors of the currently implemented codecs. Shouldn't this be handled in your training code / script?

**Comment by Freed-Wu** [comment]
> linting issues

Fixed.

> We can add ms-ssim RD-loss

Thanks.

> having the mapping between "qualities" and lambdas hard-coded might not be very helpful,

Removed.

**Review by fracape — APPROVED** [review]

**Pull request merged**
