### PR TITLE
Adding function parameter have_metrics to run methods

### PR DESCRIPTION
**Pull request by navid-mahmoudian**
Hello, 
I did a small modification and added a function parameter to `run` methods of traditional image/video codecs in `compressai/utils/bench/codecs.py`. It is because for some experiments, we might partition the image into non-overlapping tiles and encode each part separately. This was causing problem in the margins of the images because in your `compute_metrics` function, when you are computing `ms_ssim`, it is necessary that image size be larger than 160 due to the 4 downsamplings in ms-ssim.

### CODE REVIEW

**Comment by jbegaint** [comment]
Hi Navid, thanks! that's a great idea. I'd prefer to rename `have_metrics` to `return_metrics`, if that's ok with you.

**Comment by navid-mahmoudian** [comment]
Hello Jean,

Thank you very much. Sure! Do it the way you want. Thank you again for the support. Do you think you can do it soon? Such that I reinstall again the package instead of working on my own version?

Best,
Navid

**Comment by jbegaint** [comment]
hi Navid, should be done by end-of-day here.

**Comment by jbegaint** [comment]
merged manually

**Comment by navid-mahmoudian** [comment]
Thank you very much Jean

**Pull request closed without merging**
